# Site settings
title: RalPosium
email:
description: > # this means to ignore newlines until "baseurl:"
  From Stars to Life: Celebrating the Scientific Legacy of Ralph Pudritz. 
  An international workshop held at McMaster University, Hamilton, ON, Canada, June 25-27, 2025.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: RalPosium2025
email: ralposium2025@gmail.com
facebook_username:
twitter_username:
github_username: ralposium2025
address:
  - line:
  - line:
  # Feel free to add more lines here
copyright: RalPosium SOC/LOC

# API settings
google_api_key:

# Build settings
markdown: kramdown
